name: Generic System Image Builder

on:
  watch:
    types: [started]
    
env:
  ROM_LINK: your rom's direct link
  ROM_LINK: https://downloads.sourceforge.net/project/kevios12a40roms/RELEASE/evolution_a40-ota-rq3a.210905.001-09191220-unofficial-unsigned.zip?ts=gAAAAABhSKfwG2QmwbDIWKLOsgwwVZpzfw45QWhlvk2t-51g5yZWGXMnwAyLCRp3mGdunmuAJJO_fBy4HdKWcfKfI9YvuCEywg%3D%3D&use_mirror=autoselect&r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fkevios12a40roms%2Ffiles%2FRELEASE%2Fevolution_a40-ota-rq3a.210905.001-09191220-unofficial-unsigned.zip%2Fdownload
  ROM_TYPE: Generic
  BUILD_AB: true
  BUILD_AONLY: false
  ROM_AONLY: A.7z
  ROM_AB: AB.7z
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
       - name: Repo fetching...
         uses: actions/checkout@master

       - name: Clearing stuff...
         continue-on-error: true
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Setting up environment...
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk p7zip
       
       - name: Cloning repo...
         run: git clone --recurse-submodules https://github.com/ping2109/ErfanGSIs-TrebleExp.git ErfanGSIs
       
       - name: Installing requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Downloading rom and building A Only GSI
         if: env.BUILD_AONLY == 'true'
         run: sudo ./ErfanGSIs/url2GSI.sh -a $ROM_LINK $ROM_TYPE -d
       
       - name: 7zipping Aonly GSI
         if: env.BUILD_AONLY == 'true'
         run: 7za a -t7z -r $ROM_AONLY ErfanGSIs/output/*
       
       - name: Uploading Aonly GSI
         if: env.BUILD_AONLY == 'true'
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer gof $ROM_AONLY
           
       - name: Cleaning output
         if: env.BUILD_AB == 'true'
         run: sudo rm -rf ErfanGSIs/output/*
         
       - name: Downloading rom and building A/B GSI
         if: env.BUILD_AB == 'true'
         run: sudo ./ErfanGSIs/url2GSI.sh -b $ROM_LINK $ROM_TYPE -d

       - name: 7zipping AB GSI
         if: env.BUILD_AB == 'true'
         run: 7za a -t7z -r $ROM_AB ErfanGSIs/output/*

       - name: Uploading AB 
         if: env.BUILD_AB == 'true'
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer gof $ROM_AB
              
           
